service: aws-aplicador-cv

frameworkVersion: '4'


provider:
  name: aws
  runtime: python3.9
  profile: masi-personal
  region: us-east-2

#plugins:
#  - serverless-offline

functions:
  rateHandler:
    handler: handler.run
    #events:
    #  # Invoke Lambda function every minute
    #  - schedule: rate(1 minute)